services:
    tas2580.paypal.listener:
        class: rinsrans\textbox\event\listener
        arguments:
            - @config
            - @template
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: event.listener }